"""added reference fields

Revision ID: 44767e9a88da
Revises: cd845926eb45
Create Date: 2025-01-26 21:31:25.038043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44767e9a88da'
down_revision = 'cd845926eb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        # Add 'reservation_ref' column
        batch_op.add_column(sa.Column('reservation_ref', sa.String(length=50), nullable=False))
        # Create a unique constraint with a specific name
        batch_op.create_unique_constraint('uq_reservations_reservation_ref', ['reservation_ref'])

    with op.batch_alter_table('trips', schema=None) as batch_op:
        # Add 'trip_ref' column
        batch_op.add_column(sa.Column('trip_ref', sa.String(length=50), nullable=False))
        # Create a unique constraint with a specific name
        batch_op.create_unique_constraint('uq_trips_trip_ref', ['trip_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        # Drop the unique constraint using its name
        batch_op.drop_constraint('uq_trips_trip_ref', type_='unique')
        # Drop the 'trip_ref' column
        batch_op.drop_column('trip_ref')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        # Drop the unique constraint using its name
        batch_op.drop_constraint('uq_reservations_reservation_ref', type_='unique')
        # Drop the 'reservation_ref' column
        batch_op.drop_column('reservation_ref')

    # ### end Alembic commands ###
